language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: aIiR+MUEGvmcmDnfTXysJ4llLPoE6Spy8MvsJvCzpeOnQbbhEEtXDngvIGx6oiEAmS2FsXGC3ZJEwF+r1tQm/ZOcu35QVbJxsVTSsqshRGgrXvKXkcIJ51NhnxyZzcJGMO0fyVLfmh7+GBy5/DvuPmm3YJtXcDcEgu+7x+iISdk6XFExhkWdfVC/bHtbwcM+c7uzgxRVocI4FztEtzFkTCvI8S2fU4pNBoxamFwSfGTaW+ZJ4ptL13NFMM61pV9YZo8U7zbCIygxA9ssK0pvZTAkoIx6dsHimdqhrxKLc0y6XgCqjRqjrqL234GR999d5ZA0PRimV4ZNcj6Ztsyobg+GzoPtl1AmiTGHrqIzlyiFNwrOWI0HiKk42pjIsM17cvtAB6RbJQu2qQ2oZzoU6khh4FQyATiixWIcq6u8EbgNRVjEDMwUY2ZL7lceQCEGsvdUy4OfFSt0Af6y5UuuxaaloS1joFSI4PGEN85xzmNjK1WLijFuSKx6aN/vDDdPv9/pxbsG9LAdfyYFdEj2wGQ9RMmCdQRhjqN3r927R5ms6ZdEjQ+z+/F9ZsZqeIcfb4PXIhkQBB5aED25GJwkmig4EmGWiHQhnzOQf+l3Dz4w6SBF1PBFyqKs7AmQcHYDhcf4RfUZd/3xDp3Gxv+/2s0YbZgpqDfyzRf5K+Mh1OI=
notifications:
  slack:
    secure: BI/QhCr4T2nBk4SabVq7Dm9R/S+1zx3Z7/9xEMjoic5h1Byxr5v23hdxD2sv2Eq30t2byIBLnGFd5p5LdHArJV7E14Cnbgoe5pT6/E3CSQdKj6gLIxZNz6aoPJoYGcjhVCMjg4O6oPz4sQfdrNhWbHbFG0yLV2ZlkoAqf79Flb0kLuZ/W5eCPx1XF6ct5lAU09WSmHIPD0jHTd0JSmXiVdh5KXgigppiSZZ8KW0CHh8XtBcBkruBqEx8QoCCH5A3RStz/wdPoyHD5uECpcGIt59CZ+SouJQo7Y4VwIX/rrgZgFNZsG2GyrKpcrbevC03UlJyMfPGa9gB1a/NgCL0DjuQBePEWqJDebtmbKtFYEas4N5gfDAKylUvHCig6jpkLphtNALboG+Z99Oab2VEHY2e2RGlEJ588/7Bg0wQvX3bjr4RJIClp0vl+/hcSy+IW4DK3UmDHdvShFmHprI7Ruv70wfqinCMcQKw0DWiig01sxsfhjhl3ahbon4F8OWas4sHWsXjK2BDBm13iB0dKMFy9AK9b7OFKlcqVZ7xbM7Lupb+GZ7M8r1MIjVOa/dNLJqU9IJhjmTX1+jLOQzrNFYHYpy8O6iUDoq+AjOhiSf+ZiJwXXOBE349py3EWR0gXg8jGAfWqxrhkkc97gBbPi08zo7KNB6BS2e9EKoxUWY=
deploy:
- provider: npm
  api_key:
    secure: ivnVuXNzvNiRMoP7X7edG+lN4XdfL58mFaQGcWoquz/W91NibIzpn16m+7+5wk0jizcbpcGydvXy5rh7zXc4JHd88Dg92bsIUj7spn7sHiT3acb3o75bjRtnsU6Rq+kihVpyRlW3bDW08dOEiavz+mVCZXGWLLWeLEfWJX+LDrUVc7aWMuuRdAX1tiSRwQbORYhRNjDXG+1jG0jDV+O7I7SPeN1HgMeA/IuL1jj4u30Q7dhWtjwookk0RKcoQIRYmmxu6KPhmTAPHhLACCXqKCCWt3aW3El852wdNvvv7WnjML+Xfa+xS6AB1OMySdnq9Z5Rjd1BEtUGqZPayKO6GllY+e2jYQ1jq2j9JOJ8/y8+DfjNRamLRPefIrootvbwIX1DqNZYDGfaisXfkvl0b8z0w7NNZevNHRdVgIZpqK16FkuewXTVMJqgDWcRaNHfKrVQtjy25vkQPjMYJYUZ+yozJonywYP/w0O/x4528iC6hqMKGw23Kcsejiy/43jeiaL8ESYxWEkBUyYJHSDePJ/V7RHL6Kc1tRctZsecgDVA5U4/jEo1z4A2WKeINSOLaQldeVcnU712irXCVV7Q7N5ekDsIxHvcWduqstGDEwlhFBqw45iElaF+2+XcdbfdnZJeTOhsmsz29iT3tPWgaJCuLvlrah16H0Sq8/vQk1I=
  email:
    secure: bT8niNh/NIErntL5DnNMIa219n7e1VyUSH+Tk5hHFqQj1vyiwJ001yoOvdtP7QaoGDTv1XBTOBZyp32vedna6k6n3Zjy4vaIOyhwb7mZ0iRR+cbcvSK1E8xLG6dUqnwB++gvHROPYvJWDTx+lfBq/h0IHCyrB0SWyEyeHzfuREri61nERijS4hGqvQEuIULgvqe6fBPUnbZ8QZjWr1Dxghe5gS+Ta2GVHvjNQzM699a7k1glxbqXqtWIdXAGHXVa3vnK9UpbhIHUR0tJPIvBckf3K5P6VvhCvMVtNKJpeXeCvjAqg65F4jVsgVBHdRUjF5lQjcFHGYBQ1bzOjjtZemWthikbsKpSbZB4MjqWIUwH6nfk8ccKXm9XViOFc3u3T4taBMOKIzVhut9VbXysnv2uhQ/PuNlfKaloAUw4YKMXFvMX+7xqixbhPEv/xHbEw3a5xOoOt2gOVhli+Xzo7R4+NcuovDX6HsMIHZOKKsOFEgm/CpemmtMuI1+iJTygHMrw3SjpTQzoNPhjFBdnO5QeXj/28AZObPo9N0ZOH3CQiyoikY99Qnx44FRZ9MHUQ/5tHBFHPFck4U+tOUa1MJx8je7mCkNMFXIaS0AORGrEd3janqcN56S+s7xeI2qtXpihaEnSu8837zMTZMpMWLN9NwZc3PoP5nDO06tHV5o=
  on:
    branch: master
