language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: oTVWmLMH1/+4JUg/rrVEOndCmWiKhxmk/YIP3/KzCYhTQfRFR7SmR9zCKhu1lq3lVdDjq0COxxgg7vHgj7cjnv4HnsizYW6l16e8z9RvWso8wvAgUX+QGKqP9s+WXkRrX9oS+r1wuPbupPf1vna+nCxHQpeZQBM/t3HfzUyYXiiNISKClotdtkU8+5q9xN+tw2zR8dnX56JC8nSoUku0gK5V2+ErffRXALBoZx0IgfjPebAEbzQpsgkzH+gQ6/uchh/xCStaRsPuhHT2bFgwC3LXWiO0Ay7IOH+D46GtUcuYP5fcYTqBqyJ03z0zhSFnvyfvgAnwrY1Aw/fsavzcp4Xk6SxqjCkVAXidIpe+Rj5BeKtAokH1G3dJICOvxm1VeMjjesgUYfnNIpRonLeRh59g3URPSSD0Id1RT5bIYsmXen8qhILwdmlqmPCfwnhxsen5yBRG7bBZCvKPpFyLn3yesOG3F6WZuyae9lU0M543ZoOwgvQ+hO6fOYojgGUvQZeTcGMSJcdwywo3fb+vxeITaiMCu91dt9RmUoIlcAo+5GYeIz4YG1KROWb7gx+siSCCZTXrqJQ2IhLREEbBBFNaAT1iWSec3oaWzLdngM1YKArKhJujfaqb0ymxdCpEMvYqsfbIiDlRajZQtq2pfGP19Q6ued1RYldvXJyIrEA=
notifications:
  slack:
    secure: dxRdjg+ZuzpU+uS7/GkYFAPhrq3B/m43U4fa7omrtvOrrsK+6DMZibYmJCACk2ykBRVd4G6/79MDzcU3SnrSPHQpNrW2aOJ4vfZEch2pKoLvav62f3/2PWoTWQjzyVrleS64L1+NME91jq3YukqZLuXHB3UVBHbjZjEMXsKJZfSglwSOHqpUuMfgGaGeF5dQCp0f0hYUYdkfwD7rfyQJSJl5udkzRIYAXR7zrLrhQr73YjqMKZ/GrbfECBzSwitJOziYgy4zr8JlFEaC7hOVa9G/LQooZ0bk8GBVnkTVGwjh2Z0esZyMJqe+rZB3md7qvooWjpxS5WRbdwI5cfdVpZ80/fR0g8ZMtQRiWQBRy6NteytWKjP/qUl6ZKL7QVnUqgfX2CABxomIt4j/CuDz7kvwz52OKpKtQjYCcDgJh/OQFAX+Pyi9zhAtmNKayEH9W7U68eyGALj8vJoTm95YAIpucyYPh9dpfB0gySw3RePjI97Ay917el7N+T4UeSOtzIg6PQqAKIfeCi1VAVBrFExedb6rFZpDm+3xOAxfJE6vjHiLDyyjyWIZ2dkQ/6C7nM5SV3qfwB+PZpzKbLfRDhGwPU83K0OA0FfFqWOVRJyABP5RgZXcMNhpRlz+v25h6eUJkYd48+5nLX2q22P7hB6/yliUWIerK5Dmf6kQP94=
